"""sync prod schema

Revision ID: 817356a89c73
Revises: 818f2efe08d8
Create Date: 2026-04-17 22:18:50.441764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '817356a89c73'
down_revision: Union[str, None] = '818f2efe08d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'reference',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index('ix_products_reference', table_name='products')
    op.create_index(op.f('ix_products_reference'), 'products', ['reference'], unique=True)
    op.drop_column('products', 'unit')
    op.drop_column('products', 'expiry_date')
    op.drop_column('products', 'lot_number')
    op.add_column('stock_movements', sa.Column('lot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stock_movements', 'product_lots', ['lot_id'], ['id'])
    op.drop_column('stock_movements', 'lot_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_movements', sa.Column('lot_number', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_column('stock_movements', 'lot_id')
    op.add_column('products', sa.Column('lot_number', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_products_reference'), table_name='products')
    op.create_index('ix_products_reference', 'products', ['reference'], unique=False)
    op.alter_column('products', 'reference',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
